version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    volumes:
      - ./frontend/src:/app/src
    environment:
      NODE_OPTIONS: --openssl-legacy-provider
      CHOKIDAR_USEPOLLING: 1
    stdin_open: true
    tty: true
    depends_on:
      - apis_gateway
  apis_gateway:
    build: ./apis_gateway
    depends_on:
      - products
      - authentication
    environment:
      - FLASK_APP=gateway/entrypoints/flask_app.py
      - FLASK_DEBUG=1
    volumes:
      - ./apis_gateway/src:/src
    entrypoint: 
      - flask
      - run
      - --host=0.0.0.0
      - --port=80
    ports:
      - '4261:80'
  authentication:
    build: ./authentication
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_USER=admin
      - DB_PASSWORD=abc123
      - DB_PORT=5432
      - DB_NAME=shop_db
      - EMAIL_HOST=localhost
      - EMAIL_PORT=25
      - EMAIL_USER=authentication@example.com
      - API_HOST=api
      - JWT_SECRET=secret
      - FLASK_APP=authentication/entrypoints/flask_app.py
      - FLASK_DEBUG=1
    volumes:
      - ./authentication/src:/src
    entrypoint: 
      - flask
      - run
      - --host=0.0.0.0
      - --port=80
  products:
    build: ./products
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_USER=admin
      - DB_PASSWORD=abc123
      - DB_PORT=5432
      - DB_NAME=shop_db
      - API_HOST=api
      - FLASK_APP=products/entrypoints/flask_app.py
      - FLASK_DEBUG=1
    volumes:
      - ./products/src:/src
    entrypoint: 
      - flask
      - run
      - --host=0.0.0.0
      - --port=80
  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=abc123
      - POSTGRES_DB=shop_db
    volumes:
      - shop_data:/var/lib/postgresql/data/

volumes:
  shop_data: